version: '3'

services:
  hbase:
    image: harisekhon/hbase:1.4
    ports:
      - 9090:9090
      - 9095:9095
      - 2181:2181
      - 16201:16201
    container_name: hbase

  hbase-populate:
    image: hbase-populate
    build:
      context: scripts
      dockerfile: Dockerfile_populate_hbase
    container_name: hbase-populate
    depends_on:
      - hbase
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    command: "--dump-table-contents --completed-flag data/ready --remove-output-file data/ucdata-file-output.txt"

  hbase-to-mongo-export-file:
    image: hbase-to-mongo-export
    build:
      context: .
      args:
        - HBASE_TO_MONGO_EXPORT_VERSION
    container_name: hbase-to-mongo-export-file
    depends_on:
      - hbase
      - hbase-populate
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    command: >-
      --spring.profiles.active=phoneyCipherService,phoneyDataKeyService,localDataSource,outputToFile,batchRun,strongRng
      --source.table.name=ucdata
      --data.ready.flag.location=data/ready
      --file.output=data/ucdata-file-output.txt

  hbase-to-mongo-export-directory:
    image: hbase-to-mongo-export
    build:
      context: .
      args:
        - HBASE_TO_MONGO_EXPORT_VERSION
    container_name: hbase-to-mongo-export-directory
    depends_on:
      - hbase
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    command: >-
      --spring.profiles.active=phoneyCipherService,phoneyDataKeyService,localDataSource,outputToDirectory,batchRun,strongRng
      --source.table.name=ucdata
      --data.ready.flag.location=data/ready
      --directory.output=data
      --encrypt.output=false
      --compress.output=false
      --output.batch.size.max.bytes=2048

  hbase-to-mongo-export-s3:
    image: hbase-to-mongo-export
    build:
      context: .
      args:
        - HBASE_TO_MONGO_EXPORT_VERSION
    container_name: hbase-to-mongo-export-s3
    depends_on:
      - hbase
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    command: >-
      --spring.profiles.active=phoneyCipherService,phoneyDataKeyService,localDataSource,outputToS3,batchRun,strongRng
      --source.table.name=ucdata
      --data.ready.flag.location=data/ready
      --encrypt.output=true
      --compress.output=true
      --output.batch.size.max.bytes=2048
      --data.key.service.url=${DATA_KEY_SERVICE_URL}
      --aws.region=${AWS_DEFAULT_REGION}
      --s3.bucket=${S3_BUCKET}
      --s3.prefix.folder=${S3_PREFIX_FOLDER}
    environment:
      - AWS_REGION=${AWS_DEFAULT_REGION}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}

  hbase-to-mongo-export-itest:
    image: hbase-to-mongo-export-itest
    build:
      context: .
      dockerfile: Dockerfile_itests
    container_name: hbase-to-mongo-export-itests
    depends_on:
      - hbase-to-mongo-export-file
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    command: "integration"

volumes:
  shared-volume:
