version: '3'

services:

  hbase:
    image: harisekhon/hbase:1.4
    ports:
      - 9090:9090
      - 9095:9095
      - 2181:2181
      - 16201:16201
    container_name: hbase

  aws:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    container_name: aws
    environment:
      - SERVICES=s3,dynamodb,sqs

  aws-init:
    image: aws-init
    build:
      context: images/aws
    container_name: aws-init
    depends_on:
      - aws

  hbase-init:
    image: hbase-init
    build:
      context: images/hbase
    container_name: hbase-init
    depends_on:
      - hbase
      - dks-standalone-http

  export-s3:
    image: hbase-to-mongo-export
    build:
      context: images/htme
    container_name: export-s3
    depends_on:
      - hbase-init
      - dks-standalone-https
      - aws-init
    environment:
      - SPRING_CONFIG_LOCATION=config/application-s3.properties
      - CORRELATION_ID=s3-export
      - TOPIC_NAME=db.database.collection
      - APPLICATION=htme-export-s3
      - APP_VERSION=test
      - COMPONENT=jar-file
      - ENVIRONMENT=local-docker

  table-unavailable:
    image: hbase-to-mongo-export
    build:
      context: images/htme
    container_name: table-unavailable
    depends_on:
      - hbase-init
      - dks-standalone-https
      - aws-init
    environment:
      - SPRING_CONFIG_LOCATION=config/application-table-unavailable.properties
      - CORRELATION_ID=table-unavailable
      - TOPIC_NAME=does.not.exist
      - APPLICATION=htme-table-unavailable
      - APP_VERSION=test
      - COMPONENT=jar-file
      - ENVIRONMENT=local-docker

  blocked-topic:
    image: hbase-to-mongo-export
    build:
      context: images/htme
    container_name: blocked-topic
    depends_on:
      - hbase-init
      - dks-standalone-https
      - aws-init
    environment:
      - SPRING_CONFIG_LOCATION=config/application-blocked-topic.properties
      - CORRELATION_ID=blocked_topic
      - TOPIC_NAME=db.blocked.topic
      - APPLICATION=htme-blocked-topic
      - APP_VERSION=test
      - COMPONENT=jar-file
      - ENVIRONMENT=local-docker

  integration-tests:
    image: integration-tests
    build:
      context: .
      dockerfile: images/tests/Dockerfile
    container_name: integration-tests
    depends_on:
      - hbase
    command: "gradle --rerun-tasks integration"

  dks-standalone-http:
    image: dks-standalone-http
    ports:
      - 8090:8080
    build:
      context: images/dks
    container_name: dks-standalone-http
    environment:
      - SPRING_PROFILES_ACTIVE=STANDALONE,INSECURE,LocalAWS

  dks-standalone-https:
    image: dks-standalone-https
    ports:
      - 8091:8443
    build:
      context: images/dks
    container_name: dks-standalone-https
    environment:
      - SPRING_CONFIG_LOCATION=application_dks.properties
