version: '3'

services:

  hbase:
    image: harisekhon/hbase:1.4
    ports:
      - "9090:9090"
      - "9095:9095"
      - "2181:2181"
      - "16201:16201"
    container_name: hbase

  prometheus:
    build:
      context: images/prometheus
    container_name: prometheus

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
    container_name: pushgateway

  aws:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    container_name: aws
    environment:
      - SERVICES=s3,dynamodb,sqs,sns

  aws-init:
    image: aws-init
    build:
      context: images/aws
    container_name: aws-init

  hbase-init:
    image: hbase-init
    build:
      context: images/hbase
    container_name: hbase-init

  export-s3:
    image: hbase-to-mongo-export
    build:
      context: images/htme
    container_name: export-s3
    command: >-
      --send.success.indicator=true
      --scan.width=40
      --topic.arn.completion.full=arn:aws:sns:us-east-1:000000000000:full-completion-topic
      --topic.arn.monitoring=arn:aws:sns:us-east-1:000000000000:monitoring-topic
      --topic.name=db.database.collection
    environment:
      - CORRELATION_ID=s3-export

  export-nothing:
    image: hbase-to-mongo-export
    build:
      context: images/htme
    container_name: export-nothing
    command: >-
      --scan.time.range.end=2021-01-20T10:15:30+00:00
      --scan.time.range.start=2021-01-20T09:15:30+00:00
      --scan.width=256
      --topic.name=db.database.empty
    environment:
      - CORRELATION_ID=empty-export

  table-unavailable:
    image: hbase-to-mongo-export
    build:
      context: images/htme
    container_name: table-unavailable
    command: >-
      --scan.width=256
      --topic.name=does.not.exist
    environment:
      - CORRELATION_ID=table-unavailable

  blocked-topic:
    image: hbase-to-mongo-export
    build:
      context: images/htme
    container_name: blocked-topic
    command: >-
      --scan.width=256
      --topic.name=db.blocked.topic
    environment:
      - CORRELATION_ID=blocked_topic

  integration-tests:
    image: integration-tests
    build:
      context: .
      dockerfile: images/tests/Dockerfile
    container_name: integration-tests
    command: "gradle --rerun-tasks integration"

  dks:
    image: dks
    ports:
      - 8091:8443
    build:
      context: images/dks
    container_name: dks
