version: '3'

services:
  hbase:
    image: harisekhon/hbase:1.4
    ports:
      - 9090:9090
      - 9095:9095
      - 2181:2181
      - 16201:16201
    container_name: hbase

  hbase-populate:
    image: hbase-populate
    build:
      context: scripts
      dockerfile: Dockerfile_populate_hbase
    container_name: hbase-populate
    depends_on:
      - hbase
      - dks-standalone-http
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    command: >-
      --data-key-service http://dks-standalone-http:8080/datakey
      --zookeeper-quorum hbase
      --dump-table-contents
      --completed-flag data/ready
      --remove-output-file data/ucdata-file-output.txt
      --data-table ucfs-data
      --topics-table ucfs-topics
      --test-configuration-file test-config.json

  hbase-to-mongo-export-file:
    image: hbase-to-mongo-export
    build:
      context: .
      args:
        - HBASE_TO_MONGO_EXPORT_VERSION
    container_name: hbase-to-mongo-export-file
    depends_on:
      - hbase
      - dks-standalone-https
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    command: >-
      --spring.profiles.active=production,aesCipherService,httpDataKeyService,realHbaseDataSource,outputToFile,batchRun,strongRng,secureHttpClient
      --hbase.zookeeper.quorum=hbase
      --data.table.name=ucfs-data
      --column.family=topic
      --topic.name=db.core.addressDeclaration
      --data.ready.flag.location=data/ready
      --data.key.service.url=https://dks-standalone-https:8443
      --file.output=data/ucdata-file-output.txt
      --output.batch.size.max.bytes=2048
      --identity.keystore=/opt/hbase-to-mongo-export/certs/keystore.jks
      --identity.store.password=changeit
      --identity.key.password=changeit
      --identity.store.alias=cid
      --trust.keystore=/opt/hbase-to-mongo-export/certs/truststore.jks
      --trust.store.password=changeit

  hbase-to-mongo-export-directory:
    image: hbase-to-mongo-export
    build:
      context: .
      args:
        - HBASE_TO_MONGO_EXPORT_VERSION
    container_name: hbase-to-mongo-export-directory
    depends_on:
      - hbase
      - dks-standalone-https
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    command: >-
      --spring.profiles.active=production,aesCipherService,httpDataKeyService,realHbaseDataSource,outputToDirectory,batchRun,strongRng,secureHttpClient
      --hbase.zookeeper.quorum=hbase
      --data.table.name=ucfs-data
      --column.family=topic
      --topic.name=db.core.addressDeclaration
      --data.ready.flag.location=data/ready
      --directory.output=data
      --encrypt.output=true
      --compress.output=true
      --output.batch.size.max.bytes=2048
      --data.key.service.url=https://dks-standalone-https:8443
      --identity.keystore=/opt/hbase-to-mongo-export/certs/keystore.jks
      --identity.store.password=changeit
      --identity.key.password=changeit
      --identity.store.alias=cid
      --trust.keystore=/opt/hbase-to-mongo-export/certs/truststore.jks
      --trust.store.password=changeit

  hbase-to-mongo-export-s3:
    image: hbase-to-mongo-export
    build:
      context: .
      args:
        - HBASE_TO_MONGO_EXPORT_VERSION
    container_name: hbase-to-mongo-export-s3
    depends_on:
      - hbase
      - dks-standalone-https
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    command: >-
      --spring.profiles.active=aesCipherService,httpDataKeyService,realHbaseDataSource,outputToS3,batchRun,strongRng,secureHttpClient
      --hbase.zookeeper.quorum=hbase
      --data.table.name=ucfs-data
      --column.family=topic
      --topic.name=db.core.addressDeclaration
      --encrypt.output=true
      --compress.output=true
      --output.batch.size.max.bytes=2048
      --identity.keystore=/opt/hbase-to-mongo-export/certs/keystore.jks
      --identity.store.password=changeit
      --identity.key.password=changeit
      --identity.store.alias=cid
      --trust.keystore=/opt/hbase-to-mongo-export/certs/truststore.jks
      --trust.store.password=changeit
      --data.key.service.url=${DATA_KEY_SERVICE_URL_SSL}
      --aws.region=${AWS_DEFAULT_REGION}
      --s3.bucket=${S3_BUCKET}
      --s3.prefix.folder=${S3_PREFIX_FOLDER}
    environment:
      - AWS_REGION=${AWS_DEFAULT_REGION}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}

  hbase-to-mongo-export-itest:
    image: hbase-to-mongo-export-itest
    build:
      context: .
      dockerfile: Dockerfile_itests
    container_name: hbase-to-mongo-export-itests
    depends_on:
      - hbase
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
      - ./resources/certs/htme:/opt/hbase-to-mongo-export/certs
    command: "integration"
    environment:
      - FILE_NAME=data/ucdata-file-output.txt
      - EXPECTED_TIMESTAMP=10
      - EXPECTED_LINE_COUNT=7

  dks-standalone-http:
    image: dks-standalone-http
    ports:
      - 8090:8080
    build:
      context: .
      dockerfile: scripts/Dockerfile_dks
    container_name: dks-standalone-http
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    environment:
      - SPRING_PROFILES_ACTIVE=STANDALONE,INSECURE

  dks-standalone-https:
    image: dks-standalone-https
    ports:
      - 8091:8443
    build:
      context: .
      dockerfile: scripts/Dockerfile_dks
    container_name: dks-standalone-https
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    environment:
      - SPRING_CONFIG_LOCATION=application_dks.properties

volumes:
  shared-volume:
