version: '3'

services:
  hbase:
    image: harisekhon/hbase:1.4
    ports:
      - 9090:9090
      - 9095:9095
      - 2181:2181
      - 16201:16201
    container_name: hbase

  s3-dummy:
    image: localstack/localstack:latest
    ports:
      - '4563-4584:4563-4584'
      - '8055:8080'
    container_name: s3-dummy
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/opt/s3/data

  s3-bucket-provision:
    image: s3-bucket-provision
    build:
      context: resources
      dockerfile: Dockerfile_s3_bucket_provision
    container_name: s3-bucket-provision
    depends_on:
      - s3-dummy
    environment:
      - S3_SERVICE_ENDPOINT=http://s3-dummy:4572
      - AWS_REGION=${AWS_DEFAULT_REGION}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=DummyKey
      - AWS_SECRET_ACCESS_KEY=DummySecret
      - S3_BUCKET=${S3_BUCKET}
      - S3_MANIFEST_BUCKET=${S3_MANIFEST_BUCKET}

  hbase-populate:
    image: hbase-populate
    build:
      context: resources
      dockerfile: Dockerfile_populate_hbase
    container_name: hbase-populate
    depends_on:
      - hbase
      - dks-standalone-http
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    command: >-
      --data-key-service http://dks-standalone-http:8080/datakey
      --zookeeper-quorum hbase
      --dump-table-contents
      --completed-flag /opt/hbase-to-mongo-export/data/ready
      --remove-output-file /opt/hbase-to-mongo-export/data/ucdata-file-output.txt
      --data-table-name ucfs-data
      --topics-table-name ucfs-topics
      --test-configuration-file test-config.json

  hbase-to-mongo-export-file:
    image: hbase-to-mongo-export
    build:
      context: .
      args:
        - HBASE_TO_MONGO_EXPORT_VERSION
    container_name: hbase-to-mongo-export-file
    depends_on:
      - hbase
      - dks-standalone-https
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    command: >-
      --spring.profiles.active=aesCipherService,httpDataKeyService,realHbaseDataSource,outputToFile,batchRun,strongRng,secureHttpClient,bz2Compressor
      --hbase.zookeeper.quorum=hbase
      --data.table.name=ucfs-data
      --column.family=topic
      --topic.name=db.penalties-and-deductions.sanction
      --data.ready.flag.location=/opt/hbase-to-mongo-export/data/ready
      --data.key.service.url=https://dks-standalone-https:8443
      --file.output=/opt/hbase-to-mongo-export/data
      --output.batch.size.max.bytes=2048
      --identity.keystore=certs/keystore.jks
      --identity.store.password=changeit
      --identity.key.password=changeit
      --identity.store.alias=cid
      --trust.keystore=certs/truststore.jks
      --trust.store.password=changeit
      --encrypt.output=false
      --compress.output=false

  hbase-to-mongo-export-directory:
    image: hbase-to-mongo-export
    build:
      context: .
      args:
        - HBASE_TO_MONGO_EXPORT_VERSION
    container_name: hbase-to-mongo-export-directory
    depends_on:
      - hbase
      - dks-standalone-https
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    command: >-
      --spring.profiles.active=aesCipherService,httpDataKeyService,realHbaseDataSource,outputToDirectory,batchRun,strongRng,secureHttpClient,bz2Compressor
      --hbase.zookeeper.quorum=hbase
      --data.table.name=ucfs-data
      --column.family=topic
      --topic.name=db.core.addressDeclaration
      --data.ready.flag.location=/opt/hbase-to-mongo-export/data/ready
      --directory.output=/opt/hbase-to-mongo-export/data
      --encrypt.output=true
      --compress.output=true
      --output.batch.size.max.bytes=2048
      --data.key.service.url=https://dks-standalone-https:8443
      --identity.keystore=certs/keystore.jks
      --identity.store.password=changeit
      --identity.key.password=changeit
      --identity.store.alias=cid
      --trust.keystore=certs/truststore.jks
      --trust.store.password=changeit

  hbase-to-mongo-export-s3:
    image: hbase-to-mongo-export
    build:
      context: .
      args:
        - HBASE_TO_MONGO_EXPORT_VERSION
    container_name: hbase-to-mongo-export-s3
    depends_on:
      - hbase
      - dks-standalone-https
      - s3-dummy
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    command: >-
      --spring.profiles.active=aesCipherService,httpDataKeyService,realHbaseDataSource,dummyS3Client,outputToS3,batchRun,strongRng,secureHttpClient,bz2Compressor
      --hbase.zookeeper.quorum=hbase
      --data.table.name=ucfs-data
      --column.family=topic
      --topic.name=db.penalties-and-deductions.sanction
      --data.ready.flag.location=/opt/hbase-to-mongo-export/data/ready
      --data.key.service.url=https://dks-standalone-https:8443
      --encrypt.output=true
      --compress.output=true
      --output.batch.size.max.bytes=2048
      --identity.keystore=certs/keystore.jks
      --identity.store.password=changeit
      --identity.key.password=changeit
      --identity.store.alias=cid
      --trust.keystore=certs/truststore.jks
      --trust.store.password=changeit
      --data.key.service.url=${DATA_KEY_SERVICE_URL_SSL}
      --aws.region=${AWS_DEFAULT_REGION}
      --s3.bucket=${S3_BUCKET}
      --s3.prefix.folder=${S3_PREFIX_FOLDER}
      --s3.service.endpoint=http://s3-dummy:4572
      --s3.access.key=DummyKey
      --s3.secret.key=DummySecret
      --s3.manifest.prefix.folder=test-manifest-exporter
      --s3.manifest.bucket=manifestbucket

  hbase-to-mongo-export-itest:
    image: hbase-to-mongo-export-itest
    build:
      context: .
      dockerfile: Dockerfile_itests
    container_name: hbase-to-mongo-export-itests
    depends_on:
      - hbase
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
      - ./resources/certs/htme:/opt/hbase-to-mongo-export/certs
    command: "gradle --rerun-tasks integration"
    environment:
      - FILE_NAME=/opt/hbase-to-mongo-export/data
      - EXPECTED_TIMESTAMP=10
      - EXPECTED_LINE_COUNT=7
      - SPRING_PROFILES_ACTIVE=dummyS3Client
      - SPRING_CONFIG_LOCATION=application_integration.properties

  dks-standalone-http:
    image: dks-standalone-http
    ports:
      - 8090:8080
    build:
      context: resources
      dockerfile: Dockerfile_dks
    container_name: dks-standalone-http
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    environment:
      - SPRING_PROFILES_ACTIVE=STANDALONE,INSECURE

  dks-standalone-https:
    image: dks-standalone-https
    ports:
      - 8091:8443
    build:
      context: resources
      dockerfile: Dockerfile_dks
    container_name: dks-standalone-https
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    environment:
      - SPRING_CONFIG_LOCATION=application_dks.properties

volumes:
  shared-volume:
