version: '3'

services:
  hbase:
    image: harisekhon/hbase:1.4
    ports:
      - 9090:9090
      - 9095:9095
      - 2181:2181
      - 16201:16201
    container_name: hbase

  hbase-populate:
    image: hbase-populate
    build: ./scripts
    container_name: hbase-populate
    depends_on:
      - hbase
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    command: "-d -c data/ready -o data/output.txt"

  hbase-to-mongo-export:
    image: hbase-to-mongo-export
    build:
      context: .
      args:
        - HBASE_TO_MONGO_EXPORT_VERSION
    container_name: hbase-to-mongo-export
    depends_on:
      - hbase
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    command: >-
      --spring.profiles.active=phoneyDecryptionService,phoneyDataKeyService,localDataSource,outputToFile,batchRun
      --source.table.name=ucdata
      --data.ready.flag.location=data/ready
      --file.output=data/output.txt

  hbase-to-mongo-export-itest:
    image: hbase-to-mongo-export-itest
    build:
      context: .
      dockerfile: Dockerfile_itests
    container_name: hbase-to-mongo-export-itests
    volumes:
      - shared-volume:/opt/hbase-to-mongo-export/data
    command: "integration"

volumes:
  shared-volume:
