name: Test and Scan

on: pull_request

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.4.1

      - name: Gradle build
        run: |
          gradle build

  integration-test:
    runs-on: ubuntu-latest
    needs: [build-app]
    steps:
      - uses: actions/checkout@v3
      - name: Run Integration Tests
        run: |
          make integration-all
